version: "3.9"

services:
  fastapi:
    build: .
    container_name: video_dubber_api
    command: gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8000 --workers 4
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A app.core.celery_app worker --loglevel=
    depends_on:
      - redis

  celery_beat:
    build: .
    command: celery -A app.core.celery_app beat --loglevel=info
    depends_on:
      - redis

  flower:
    build: .
    command: celery -A app.core.celery_app flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis