[project]
name = "fastapi-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aioboto3>=15.5.0",
    "alembic>=1.18.4",
    "asyncmy>=0.2.11",
    "azure-cognitiveservices-speech>=1.49.1",
    "babel>=2.18.0",
    "boto3>=1.40.61",
    "celery>=5.6.3",
    "cryptography>=47.0.0",
    "demucs>=4.0.1",
    "fastapi>=0.136.0",
    "fastapi-cache2>=0.2.2",
    "faster-whisper>=1.2.1",
    "flower>=2.0.1",
    "google-genai>=1.73.1",
    "gunicorn>=25.3.0",
    "numpy==1.26.4",
    "openai>=2.34.0",
    "pycryptodome>=3.23.0",
    "pydantic-settings>=2.14.0",
    "pydub>=0.25.1",
    "pymysql>=1.1.2",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.27",
    "redis>=7.4.0",
    "requests>=2.33.1",
    "soundfile>=0.13.1",
    "sqlalchemy>=2.0.49",
    "torch==2.2.2",
    "torchaudio==2.2.2",
    "uvicorn>=0.45.0",
]
